version: "3.8"
services:
    db:
        image: mysql:8
        env_file:
            - ./mysql.env
    php:
        build:
            context: .
            dockerfile: ./scripts/php.dockerfile
        working_dir: /var/www/html
        # Workaround for running multiple tests in a docker container: https://github.com/cypress-io/cypress/issues/350
        ipc: host
        depends_on:
            - db