version: "3.8"
services:
    db:
        image: mysql
        env_file:
            - ./mysql.env
    php:
        build:
            context: .
            dockerfile: ./scripts/php.dockerfile
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html/wp-content/plugins/coil-wordpress-plugin
        depends_on:
            - db
    cypress:
        build:
            context: .
            dockerfile: ./scripts/cypress.dockerfile
        volumes:
            - .:/app
        depends_on:
            - php