version: "3.8"
services:
    db:
        image: mysql
        env_file:
            - ./mysql.env
    php:
        build:
            context: .
            dockerfile: ./scripts/php.dockerfile
        working_dir: /var/www/html
        ports:
            - 9000:80
        depends_on:
            - db