version: 2.0
jobs:
  js_scss_linting:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing npm
          command: |
            apt update
            apt-get install docker docker-engine docker.io containerd runc
            docker run hello-world
            apt install curl libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
            curl -o install.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
            bash install.sh
            groupadd --gid 1000 node && useradd --uid 1000 --gid node -G sudo --shell /bin/bash --create-home node
            source ~/.nvm/nvm.sh && nvm install 12 && nvm use 12 && nvm install-latest-npm && npm install && npx grunt test
workflows:
  version: 2
  test:
    jobs:
      - js_scss_linting
