version: 2.0
jobs:
  cypress_tests:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Move files into a temporary directory
          command: |
            sudo mkdir /coil-wordpress-plugin
            sudo mv *.* /coil-wordpress-plugin
      - run:
          name: Run mysql and node Docker containers
          command: |
            docker run -d --name db --network host --env-file /coil-wordpress-plugin/mysql.env mysql:8
            docker run -d --name node --network host cimg/node:12.22.7
      - run:
          name: Installing wp-cli
          command: |
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
            chmod +x wp-cli.phar
            sudo mv wp-cli.phar /usr/local/bin/wp
      - run:
          name: Installing mysql-client
          command: |
            apt update
            sudo apt install -y mysql-client
      - run:
          name: Downloading wordPress core, which requires ZipArchive and copying in the plugin code
          command: |
            sudo apt install -y libzip-dev zip && docker-php-ext-install zip
            wp core download --allow-root
            sudo mv /coil-wordpress-plugin /var/www/html/wp-content/plugins
      - run:
          name: Build and run Apache container
          command: |
            docker build -t webserver:apache ./scripts
            docker run -d --name sever --network host webserver:apache
      - run:
          name: Installing Cypress dependencies and sudo
          command: sudo apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
            # curl -o install.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh
            # bash install.sh
            # groupadd --gid 1000 node && useradd --uid 1000 --gid node -G sudo --shell /bin/bash --create-home node
            # source ~/.nvm/nvm.sh && nvm install 12 && nvm use 12 && nvm install-latest-npm && npm install && npx grunt test
workflows:
  version: 2
  test:
    jobs:
      - cypress_tests
