version: 2.0
jobs:
  js_scss_linting:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing npm
          command: |
            docker run -d --name node --network host cimg/node:14.10.1
      - run: npm install
      - run: npx grunt test
workflows:
  version: 2
  test:
    jobs:
      - js_scss_linting
